prep_time: 20
cook_time: 95
default_portions: 4
categories:
  - lunch
  - dinner
  - high-protein
  - meal-prep-friendly
nutrition_per_portion:
  calories: 715
  protein_g: 70
  carbs_g: 35
  fat_g: 33
ingredients:
  - slug: beef_chuck
    amount: 1000
  - slug: onion
    amount: 80
  - slug: canola_oil
    amount: 27
  - slug: water
    amount: 2000
  - slug: tomato_paste
    amount: 18
  - slug: potato
    amount: 720
  - slug: paprika_powder
    amount: 5
  - slug: salt
    amount: 2
  - slug: black_pepper
    amount: 1
