prep_time: 15
cook_time: 20
default_portions: 6
categories:
  - lunch
  - dinner
  - vegan
  - vegetarian
nutrition_per_portion:
  calories: 365
  protein_g: 10
  carbs_g: 35
  fat_g: 21
ingredients:
  - slug: dried_shiitake_mushroom
    amount: 40
  - slug: garlic_clove
    amount: 1
  - slug: red_bell_pepper
    amount: 150
  - slug: zucchini
    amount: 230
  - slug: broccoli
    amount: 170
  - slug: mie_noodle
    amount: 150
  - slug: coconut_oil
    amount: 14
  - slug: fresh_ginger
    amount: 2
  - slug: vegetable_broth
    amount: 1000
  - slug: canned_coconut_milk
    amount: 400
  - slug: maple_syrup
    amount: 7
  - slug: soy_sauce
    amount: 60
  - slug: peanut_butter
    amount: 60
  - slug: lime
    amount: 1
  - slug: red_curry_paste
    amount: 40
