prep_time: 10
cook_time: 15
default_portions: 2
categories:
  - lunch
  - dinner
  - vegetarian
  - quick
nutrition_per_portion:
  calories: 655
  protein_g: 24
  carbs_g: 74
  fat_g: 27
ingredients:
  - slug: tagliatelle
    amount: 200
  - slug: green_asparagus
    amount: 250
  - slug: garlic_clove
    amount: 2
  - slug: olive_oil
    amount: 41
  - slug: lemon
    amount: 1
  - slug: parmesan_cheese
    amount: 50
  - slug: fresh_basil
    amount: 5
  - slug: salt
    amount: 1
  - slug: black_pepper
    amount: 1
