prep_time: 15
cook_time: 15
default_portions: 4
categories:
  - lunch
  - dinner
  - high-protein
  - quick
  - meal-prep-friendly
nutrition_per_portion:
  calories: 445
  protein_g: 64
  carbs_g: 28
  fat_g: 9
ingredients:
  - slug: chicken_breast
    amount: 1000
  - slug: onion
    amount: 160
  - slug: olive_oil
    amount: 14
  - slug: carrot
    amount: 300
  - slug: zucchini
    amount: 460
  - slug: red_bell_pepper
    amount: 300
  - slug: canned_diced_tomato
    amount: 1000
  - slug: salt
    amount: 3
  - slug: black_pepper
    amount: 2
