prep_time: 10
cook_time: 0
default_portions: 4
categories:
  - lunch
  - dinner
  - snack
  - vegetarian
  - quick
nutrition_per_portion:
  calories: 175
  protein_g: 3
  carbs_g: 5
  fat_g: 15
ingredients:
  - slug: cucumber
    amount: 600
  - slug: chives
    amount: 10
  - slug: creme_fraiche
    amount: 200
  - slug: lemon
    amount: 80
  - slug: salt
    amount: 1
  - slug: black_pepper
    amount: 1
