prep_time: 15
cook_time: 0
default_portions: 5
categories:
  - lunch
  - dinner
  - snack
  - vegan
  - vegetarian
  - quick
  - meal-prep-friendly
nutrition_per_portion:
  calories: 182
  protein_g: 4
  carbs_g: 23
  fat_g: 9
ingredients:
  - slug: cucumber
    amount: 750
  - slug: tomato
    amount: 375
  - slug: spring_onion
    amount: 125
  - slug: canned_corn
    amount: 375
  - slug: olive_oil
    amount: 34
  - slug: balsamic_vinegar
    amount: 10
  - slug: ajvar
    amount: 100
  - slug: ground_cumin
    amount: 2
  - slug: salt
    amount: 2
